# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Command.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Command.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rCommand.proto\"\xf4\x06\n\x07\x43ommand\x12+\n#set_temperature_setpoint_fahrenheit\x18\x01 \x01(\x05\x12*\n\nset_pump_1\x18\x02 \x01(\x0e\x32\x16.Command.SetPumpStatus\x12*\n\nset_pump_2\x18\x03 \x01(\x0e\x32\x16.Command.SetPumpStatus\x12*\n\nset_pump_3\x18\x04 \x01(\x0e\x32\x16.Command.SetPumpStatus\x12*\n\nset_pump_4\x18\x05 \x01(\x0e\x32\x16.Command.SetPumpStatus\x12*\n\nset_pump_5\x18\x06 \x01(\x0e\x32\x16.Command.SetPumpStatus\x12,\n\x0cset_blower_1\x18\x07 \x01(\x0e\x32\x16.Command.SetPumpStatus\x12,\n\x0cset_blower_2\x18\x08 \x01(\x0e\x32\x16.Command.SetPumpStatus\x12\x12\n\nset_lights\x18\t \x01(\x08\x12\x12\n\nset_stereo\x18\n \x01(\x08\x12\x12\n\nset_filter\x18\x0b \x01(\x08\x12\x11\n\tset_onzen\x18\x0c \x01(\x08\x12\x11\n\tset_ozone\x18\r \x01(\x08\x12\x17\n\x0fset_exhaust_fan\x18\x0e \x01(\x08\x12/\n\x0fset_sauna_state\x18\x0f \x01(\x0e\x32\x16.Command.SetSaunaState\x12\x1b\n\x13set_sauna_time_left\x18\x10 \x01(\x05\x12\x12\n\nset_all_on\x18\x11 \x01(\x08\x12\x12\n\nset_fogger\x18\x12 \x01(\x08\x12\x18\n\x10set_spaboy_boost\x18\x13 \x01(\x08\x12\x16\n\x0eset_pack_reset\x18\x14 \x01(\x08\x12\x14\n\x0cset_log_dump\x18\x15 \x01(\x08\x12\x0f\n\x07set_sds\x18\x16 \x01(\x08\x12\x10\n\x08set_yess\x18\x17 \x01(\x08\":\n\rSetPumpStatus\x12\x0c\n\x08PUMP_OFF\x10\x00\x12\x0c\n\x08PUMP_LOW\x10\x01\x12\r\n\tPUMP_HIGH\x10\x02\"l\n\rSetSaunaState\x12\x0e\n\nSAUNA_IDLE\x10\x00\x12\x0f\n\x0bSAUNA_TIMER\x10\x01\x12\x12\n\x0eSAUNA_PRESET_A\x10\x02\x12\x12\n\x0eSAUNA_PRESET_B\x10\x03\x12\x12\n\x0eSAUNA_PRESET_C\x10\x04'
)



_COMMAND_SETPUMPSTATUS = _descriptor.EnumDescriptor(
  name='SetPumpStatus',
  full_name='Command.SetPumpStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PUMP_OFF', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PUMP_LOW', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PUMP_HIGH', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=734,
  serialized_end=792,
)
_sym_db.RegisterEnumDescriptor(_COMMAND_SETPUMPSTATUS)

_COMMAND_SETSAUNASTATE = _descriptor.EnumDescriptor(
  name='SetSaunaState',
  full_name='Command.SetSaunaState',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SAUNA_IDLE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SAUNA_TIMER', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SAUNA_PRESET_A', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SAUNA_PRESET_B', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SAUNA_PRESET_C', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=794,
  serialized_end=902,
)
_sym_db.RegisterEnumDescriptor(_COMMAND_SETSAUNASTATE)


_COMMAND = _descriptor.Descriptor(
  name='Command',
  full_name='Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='set_temperature_setpoint_fahrenheit', full_name='Command.set_temperature_setpoint_fahrenheit', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_pump_1', full_name='Command.set_pump_1', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_pump_2', full_name='Command.set_pump_2', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_pump_3', full_name='Command.set_pump_3', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_pump_4', full_name='Command.set_pump_4', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_pump_5', full_name='Command.set_pump_5', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_blower_1', full_name='Command.set_blower_1', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_blower_2', full_name='Command.set_blower_2', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_lights', full_name='Command.set_lights', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_stereo', full_name='Command.set_stereo', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_filter', full_name='Command.set_filter', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_onzen', full_name='Command.set_onzen', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_ozone', full_name='Command.set_ozone', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_exhaust_fan', full_name='Command.set_exhaust_fan', index=13,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_sauna_state', full_name='Command.set_sauna_state', index=14,
      number=15, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_sauna_time_left', full_name='Command.set_sauna_time_left', index=15,
      number=16, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_all_on', full_name='Command.set_all_on', index=16,
      number=17, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_fogger', full_name='Command.set_fogger', index=17,
      number=18, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_spaboy_boost', full_name='Command.set_spaboy_boost', index=18,
      number=19, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_pack_reset', full_name='Command.set_pack_reset', index=19,
      number=20, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_log_dump', full_name='Command.set_log_dump', index=20,
      number=21, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_sds', full_name='Command.set_sds', index=21,
      number=22, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_yess', full_name='Command.set_yess', index=22,
      number=23, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _COMMAND_SETPUMPSTATUS,
    _COMMAND_SETSAUNASTATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=902,
)

_COMMAND.fields_by_name['set_pump_1'].enum_type = _COMMAND_SETPUMPSTATUS
_COMMAND.fields_by_name['set_pump_2'].enum_type = _COMMAND_SETPUMPSTATUS
_COMMAND.fields_by_name['set_pump_3'].enum_type = _COMMAND_SETPUMPSTATUS
_COMMAND.fields_by_name['set_pump_4'].enum_type = _COMMAND_SETPUMPSTATUS
_COMMAND.fields_by_name['set_pump_5'].enum_type = _COMMAND_SETPUMPSTATUS
_COMMAND.fields_by_name['set_blower_1'].enum_type = _COMMAND_SETPUMPSTATUS
_COMMAND.fields_by_name['set_blower_2'].enum_type = _COMMAND_SETPUMPSTATUS
_COMMAND.fields_by_name['set_sauna_state'].enum_type = _COMMAND_SETSAUNASTATE
_COMMAND_SETPUMPSTATUS.containing_type = _COMMAND
_COMMAND_SETSAUNASTATE.containing_type = _COMMAND
DESCRIPTOR.message_types_by_name['Command'] = _COMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Command = _reflection.GeneratedProtocolMessageType('Command', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND,
  '__module__' : 'Command_pb2'
  # @@protoc_insertion_point(class_scope:Command)
  })
_sym_db.RegisterMessage(Command)


# @@protoc_insertion_point(module_scope)
