# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MobileWifiDetails.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MobileWifiDetails.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17MobileWifiDetails.proto\"\xe8\x01\n\x11MobileWifiDetails\x12\x0c\n\x04ssid\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x41\n\x13wifi_details_status\x18\x03 \x01(\x0e\x32$.MobileWifiDetails.WifiDetailsStatus\x12\x11\n\tlocalssid\x18\x04 \x01(\t\x12\x14\n\x0csecuritytype\x18\x05 \x01(\t\"G\n\x11WifiDetailsStatus\x12\x18\n\x14WIFI_DETAILS_SUCCESS\x10\x00\x12\x18\n\x14WIFI_DETAILS_FAILURE\x10\x01'
)



_MOBILEWIFIDETAILS_WIFIDETAILSSTATUS = _descriptor.EnumDescriptor(
  name='WifiDetailsStatus',
  full_name='MobileWifiDetails.WifiDetailsStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WIFI_DETAILS_SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WIFI_DETAILS_FAILURE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=189,
  serialized_end=260,
)
_sym_db.RegisterEnumDescriptor(_MOBILEWIFIDETAILS_WIFIDETAILSSTATUS)


_MOBILEWIFIDETAILS = _descriptor.Descriptor(
  name='MobileWifiDetails',
  full_name='MobileWifiDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ssid', full_name='MobileWifiDetails.ssid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='MobileWifiDetails.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wifi_details_status', full_name='MobileWifiDetails.wifi_details_status', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='localssid', full_name='MobileWifiDetails.localssid', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='securitytype', full_name='MobileWifiDetails.securitytype', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MOBILEWIFIDETAILS_WIFIDETAILSSTATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=260,
)

_MOBILEWIFIDETAILS.fields_by_name['wifi_details_status'].enum_type = _MOBILEWIFIDETAILS_WIFIDETAILSSTATUS
_MOBILEWIFIDETAILS_WIFIDETAILSSTATUS.containing_type = _MOBILEWIFIDETAILS
DESCRIPTOR.message_types_by_name['MobileWifiDetails'] = _MOBILEWIFIDETAILS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MobileWifiDetails = _reflection.GeneratedProtocolMessageType('MobileWifiDetails', (_message.Message,), {
  'DESCRIPTOR' : _MOBILEWIFIDETAILS,
  '__module__' : 'MobileWifiDetails_pb2'
  # @@protoc_insertion_point(class_scope:MobileWifiDetails)
  })
_sym_db.RegisterMessage(MobileWifiDetails)


# @@protoc_insertion_point(module_scope)
