# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MobileSpaRegistration.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MobileSpaRegistration.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1bMobileSpaRegistration.proto\"\x98\x02\n\x15MobileSpaRegistration\x12\x19\n\x11registration_code\x18\x01 \x01(\t\x12\x15\n\rserial_number\x18\x02 \x01(\t\x12\x14\n\x0cspa_nickname\x18\x03 \x01(\t\x12=\n\nreg_status\x18\x04 \x01(\x0e\x32).MobileSpaRegistration.RegistrationStatus\x12\x10\n\x08spa_guid\x18\x05 \x01(\t\"f\n\x12RegistrationStatus\x12\x18\n\x14REGISTRATION_SUCCESS\x10\x00\x12\x18\n\x14REGISTRATION_FAILURE\x10\x01\x12\x1c\n\x18REGISTRATION_SPA_OFFLINE\x10\x02'
)



_MOBILESPAREGISTRATION_REGISTRATIONSTATUS = _descriptor.EnumDescriptor(
  name='RegistrationStatus',
  full_name='MobileSpaRegistration.RegistrationStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REGISTRATION_SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REGISTRATION_FAILURE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REGISTRATION_SPA_OFFLINE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=210,
  serialized_end=312,
)
_sym_db.RegisterEnumDescriptor(_MOBILESPAREGISTRATION_REGISTRATIONSTATUS)


_MOBILESPAREGISTRATION = _descriptor.Descriptor(
  name='MobileSpaRegistration',
  full_name='MobileSpaRegistration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='registration_code', full_name='MobileSpaRegistration.registration_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='serial_number', full_name='MobileSpaRegistration.serial_number', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='spa_nickname', full_name='MobileSpaRegistration.spa_nickname', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reg_status', full_name='MobileSpaRegistration.reg_status', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='spa_guid', full_name='MobileSpaRegistration.spa_guid', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MOBILESPAREGISTRATION_REGISTRATIONSTATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=312,
)

_MOBILESPAREGISTRATION.fields_by_name['reg_status'].enum_type = _MOBILESPAREGISTRATION_REGISTRATIONSTATUS
_MOBILESPAREGISTRATION_REGISTRATIONSTATUS.containing_type = _MOBILESPAREGISTRATION
DESCRIPTOR.message_types_by_name['MobileSpaRegistration'] = _MOBILESPAREGISTRATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MobileSpaRegistration = _reflection.GeneratedProtocolMessageType('MobileSpaRegistration', (_message.Message,), {
  'DESCRIPTOR' : _MOBILESPAREGISTRATION,
  '__module__' : 'MobileSpaRegistration_pb2'
  # @@protoc_insertion_point(class_scope:MobileSpaRegistration)
  })
_sym_db.RegisterMessage(MobileSpaRegistration)


# @@protoc_insertion_point(module_scope)
