# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OnzenLive.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='OnzenLive.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fOnzenLive.proto\"\xe2\x05\n\tOnzenLive\x12\x0c\n\x04guid\x18\x01 \x01(\t\x12\x0b\n\x03orp\x18\x02 \x01(\x05\x12\x0e\n\x06ph_100\x18\x03 \x01(\x05\x12\x0f\n\x07\x63urrent\x18\x04 \x01(\x05\x12\x0f\n\x07voltage\x18\x05 \x01(\x05\x12\x18\n\x10\x63urrent_setpoint\x18\x06 \x01(\x05\x12\x18\n\x10voltage_setpoint\x18\x07 \x01(\x05\x12\r\n\x05pump1\x18\x08 \x01(\x08\x12\r\n\x05pump2\x18\t \x01(\x08\x12\x19\n\x11orp_state_machine\x18\n \x01(\x05\x12\x1f\n\x17\x65lectrode_state_machine\x18\x0b \x01(\x05\x12\x14\n\x0c\x65lectrode_id\x18\x0c \x01(\x05\x12/\n\x12\x65lectrode_polarity\x18\r \x01(\x0e\x32\x13.OnzenLive.Polarity\x12 \n\x18\x65lectrode_1_resistance_1\x18\x0e \x01(\x05\x12 \n\x18\x65lectrode_1_resistance_2\x18\x0f \x01(\x05\x12 \n\x18\x65lectrode_2_resistance_1\x18\x10 \x01(\x05\x12 \n\x18\x65lectrode_2_resistance_2\x18\x11 \x01(\x05\x12\x14\n\x0c\x63ommand_mode\x18\x12 \x01(\x08\x12\x15\n\relectrode_mAH\x18\x13 \x01(\x05\x12\"\n\x08ph_color\x18\x14 \x01(\x0e\x32\x10.OnzenLive.Color\x12#\n\torp_color\x18\x15 \x01(\x0e\x32\x10.OnzenLive.Color\x12\x16\n\x0e\x65lectrode_wear\x18\x16 \x01(\x05\"8\n\x08Polarity\x12\x15\n\x11POLARITY_POSITIVE\x10\x00\x12\x15\n\x11POLARITY_NEGATIVE\x10\x01\"c\n\x05\x43olor\x12\r\n\tCOLOR_LOW\x10\x00\x12\x15\n\x11\x43OLOR_CAUTION_LOW\x10\x01\x12\x0c\n\x08\x43OLOR_OK\x10\x02\x12\x16\n\x12\x43OLOR_CAUTION_HIGH\x10\x03\x12\x0e\n\nCOLOR_HIGH\x10\x04'
)



_ONZENLIVE_POLARITY = _descriptor.EnumDescriptor(
  name='Polarity',
  full_name='OnzenLive.Polarity',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='POLARITY_POSITIVE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='POLARITY_NEGATIVE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=601,
  serialized_end=657,
)
_sym_db.RegisterEnumDescriptor(_ONZENLIVE_POLARITY)

_ONZENLIVE_COLOR = _descriptor.EnumDescriptor(
  name='Color',
  full_name='OnzenLive.Color',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COLOR_LOW', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COLOR_CAUTION_LOW', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COLOR_OK', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COLOR_CAUTION_HIGH', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COLOR_HIGH', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=659,
  serialized_end=758,
)
_sym_db.RegisterEnumDescriptor(_ONZENLIVE_COLOR)


_ONZENLIVE = _descriptor.Descriptor(
  name='OnzenLive',
  full_name='OnzenLive',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='guid', full_name='OnzenLive.guid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orp', full_name='OnzenLive.orp', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ph_100', full_name='OnzenLive.ph_100', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='current', full_name='OnzenLive.current', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='voltage', full_name='OnzenLive.voltage', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='current_setpoint', full_name='OnzenLive.current_setpoint', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='voltage_setpoint', full_name='OnzenLive.voltage_setpoint', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pump1', full_name='OnzenLive.pump1', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pump2', full_name='OnzenLive.pump2', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orp_state_machine', full_name='OnzenLive.orp_state_machine', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='electrode_state_machine', full_name='OnzenLive.electrode_state_machine', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='electrode_id', full_name='OnzenLive.electrode_id', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='electrode_polarity', full_name='OnzenLive.electrode_polarity', index=12,
      number=13, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='electrode_1_resistance_1', full_name='OnzenLive.electrode_1_resistance_1', index=13,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='electrode_1_resistance_2', full_name='OnzenLive.electrode_1_resistance_2', index=14,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='electrode_2_resistance_1', full_name='OnzenLive.electrode_2_resistance_1', index=15,
      number=16, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='electrode_2_resistance_2', full_name='OnzenLive.electrode_2_resistance_2', index=16,
      number=17, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='command_mode', full_name='OnzenLive.command_mode', index=17,
      number=18, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='electrode_mAH', full_name='OnzenLive.electrode_mAH', index=18,
      number=19, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ph_color', full_name='OnzenLive.ph_color', index=19,
      number=20, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orp_color', full_name='OnzenLive.orp_color', index=20,
      number=21, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='electrode_wear', full_name='OnzenLive.electrode_wear', index=21,
      number=22, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ONZENLIVE_POLARITY,
    _ONZENLIVE_COLOR,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=758,
)

_ONZENLIVE.fields_by_name['electrode_polarity'].enum_type = _ONZENLIVE_POLARITY
_ONZENLIVE.fields_by_name['ph_color'].enum_type = _ONZENLIVE_COLOR
_ONZENLIVE.fields_by_name['orp_color'].enum_type = _ONZENLIVE_COLOR
_ONZENLIVE_POLARITY.containing_type = _ONZENLIVE
_ONZENLIVE_COLOR.containing_type = _ONZENLIVE
DESCRIPTOR.message_types_by_name['OnzenLive'] = _ONZENLIVE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OnzenLive = _reflection.GeneratedProtocolMessageType('OnzenLive', (_message.Message,), {
  'DESCRIPTOR' : _ONZENLIVE,
  '__module__' : 'OnzenLive_pb2'
  # @@protoc_insertion_point(class_scope:OnzenLive)
  })
_sym_db.RegisterMessage(OnzenLive)


# @@protoc_insertion_point(module_scope)
