# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Peripheral.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Peripheral.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10Peripheral.proto\"\xe0\x02\n\nPeripheral\x12\x0c\n\x04guid\x18\x01 \x01(\t\x12\x18\n\x10hardware_version\x18\x02 \x01(\x05\x12\x18\n\x10\x66irmware_version\x18\x03 \x01(\x05\x12\x37\n\x0cproduct_code\x18\x04 \x01(\x0e\x32!.Peripheral.PeripheralProductCode\x12\x11\n\tconnected\x18\x05 \x01(\x08\"\xc3\x01\n\x15PeripheralProductCode\x12 \n\x1cPERIPHERAL_PRODUCT_CODE_NONE\x10\x00\x12\x1f\n\x1bPERIPHERAL_PRODUCT_CODE_SPA\x10\x01\x12#\n\x1fPERIPHERAL_PRODUCT_CODE_TOPSIDE\x10\x02\x12!\n\x1dPERIPHERAL_PRODUCT_CODE_ONZEN\x10\x03\x12\x1f\n\x1bPERIPHERAL_PRODUCT_CODE_WAA\x10\x04'
)



_PERIPHERAL_PERIPHERALPRODUCTCODE = _descriptor.EnumDescriptor(
  name='PeripheralProductCode',
  full_name='Peripheral.PeripheralProductCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PERIPHERAL_PRODUCT_CODE_NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PERIPHERAL_PRODUCT_CODE_SPA', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PERIPHERAL_PRODUCT_CODE_TOPSIDE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PERIPHERAL_PRODUCT_CODE_ONZEN', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PERIPHERAL_PRODUCT_CODE_WAA', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=178,
  serialized_end=373,
)
_sym_db.RegisterEnumDescriptor(_PERIPHERAL_PERIPHERALPRODUCTCODE)


_PERIPHERAL = _descriptor.Descriptor(
  name='Peripheral',
  full_name='Peripheral',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='guid', full_name='Peripheral.guid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hardware_version', full_name='Peripheral.hardware_version', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='firmware_version', full_name='Peripheral.firmware_version', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='product_code', full_name='Peripheral.product_code', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='connected', full_name='Peripheral.connected', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PERIPHERAL_PERIPHERALPRODUCTCODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=373,
)

_PERIPHERAL.fields_by_name['product_code'].enum_type = _PERIPHERAL_PERIPHERALPRODUCTCODE
_PERIPHERAL_PERIPHERALPRODUCTCODE.containing_type = _PERIPHERAL
DESCRIPTOR.message_types_by_name['Peripheral'] = _PERIPHERAL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Peripheral = _reflection.GeneratedProtocolMessageType('Peripheral', (_message.Message,), {
  'DESCRIPTOR' : _PERIPHERAL,
  '__module__' : 'Peripheral_pb2'
  # @@protoc_insertion_point(class_scope:Peripheral)
  })
_sym_db.RegisterMessage(Peripheral)


# @@protoc_insertion_point(module_scope)
