# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Router.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Router.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cRouter.proto\"\x98\x02\n\x06Router\x12\x0c\n\x04ssid\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12&\n\nencryption\x18\x03 \x01(\x0e\x32\x12.Router.Encryption\x12\"\n\x08protocol\x18\x04 \x01(\x0e\x32\x10.Router.Protocol\"^\n\nEncryption\x12\x13\n\x0f\x45NCRYPTION_NONE\x10\x00\x12\x12\n\x0e\x45NCRYPTION_WEP\x10\x01\x12\x12\n\x0e\x45NCRYPTION_WPA\x10\x02\x12\x13\n\x0f\x45NCRYPTION_WPA2\x10\x03\"B\n\x08Protocol\x12\x11\n\rPROTOCOL_NONE\x10\x00\x12\x10\n\x0cPROTOCOL_AES\x10\x01\x12\x11\n\rPROTOCOL_TKIP\x10\x02'
)



_ROUTER_ENCRYPTION = _descriptor.EnumDescriptor(
  name='Encryption',
  full_name='Router.Encryption',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ENCRYPTION_NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ENCRYPTION_WEP', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ENCRYPTION_WPA', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ENCRYPTION_WPA2', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=135,
  serialized_end=229,
)
_sym_db.RegisterEnumDescriptor(_ROUTER_ENCRYPTION)

_ROUTER_PROTOCOL = _descriptor.EnumDescriptor(
  name='Protocol',
  full_name='Router.Protocol',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PROTOCOL_NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PROTOCOL_AES', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PROTOCOL_TKIP', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=231,
  serialized_end=297,
)
_sym_db.RegisterEnumDescriptor(_ROUTER_PROTOCOL)


_ROUTER = _descriptor.Descriptor(
  name='Router',
  full_name='Router',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ssid', full_name='Router.ssid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='Router.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='encryption', full_name='Router.encryption', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='protocol', full_name='Router.protocol', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ROUTER_ENCRYPTION,
    _ROUTER_PROTOCOL,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=297,
)

_ROUTER.fields_by_name['encryption'].enum_type = _ROUTER_ENCRYPTION
_ROUTER.fields_by_name['protocol'].enum_type = _ROUTER_PROTOCOL
_ROUTER_ENCRYPTION.containing_type = _ROUTER
_ROUTER_PROTOCOL.containing_type = _ROUTER
DESCRIPTOR.message_types_by_name['Router'] = _ROUTER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Router = _reflection.GeneratedProtocolMessageType('Router', (_message.Message,), {
  'DESCRIPTOR' : _ROUTER,
  '__module__' : 'Router_pb2'
  # @@protoc_insertion_point(class_scope:Router)
  })
_sym_db.RegisterMessage(Router)


# @@protoc_insertion_point(module_scope)
